backend:
  name: 4m

media_folder: static/assets
public_folder: assets

collections:
  - name: fences
    label: Fences
    folder: fences
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: titel, label: Title }
      - { name: body, label: Body, widget: markdown }
